### ISSUE TITLE
[Feature Request]: Add check for postinstall command in project

### ISSUE THREAD

**Issue by OyewoleOyedeji** [BayBreezy/ui-thing-cli#1]
Hey, I love your work with the `shadcn/ui`port in Nuxt.js, but could you add a check for a `postinstall` command in the current project before trying to execute such command.

I mostly work in a mono repo, so when I try running this CLI in a workspace without the `postinstall` command, my console becomes messed up with error logs.

Thanks in advance 😅

**Comment by BayBreezy** [comment]
Hmmm..... This makes sense. I will get on it tomorrow 😄

**Comment by BayBreezy** [comment]
@OyewoleOyedeji , can you try it out with the latest release?

**Comment by OyewoleOyedeji** [comment]
Hey 👋🏾, I'll try it today, and let you know.

**Comment by OyewoleOyedeji** [comment]
@BayBreezy sorry for the delay, this feature has been implemented. Thanks 😄

**Comment by BayBreezy** [comment]
@OyewoleOyedeji Nice. Thanks for the update
