### ISSUE TITLE
CLI crash

### ISSUE THREAD

**Issue by justindefodji** [BayBreezy/ui-thing-cli#2]
SyntaxError: Named export 'readFileSync' not found. The requested module 'fs-extra' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

CLI latest version throws the above error

**Comment by BayBreezy** [comment]
I will be fixing this soon. My bad

**Comment by BayBreezy** [comment]
@justindefodji fixed in last release.

rookie mistake made there
